# Generated by Django 3.1.4 on 2020-12-15 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='email',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='message',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.CharField(max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
